// <auto-generated />
using System;
using EmprestimoDVD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmprestimoDVD.Persistence.Migrations
{
    [DbContext(typeof(EmprestimoDVDContext))]
    [Migration("20230416004208_AlterDataDevolver")]
    partial class AlterDataDevolver
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmprestimoDVD.Domain.Entidades.DVD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistaPrincipalId")
                        .HasColumnType("int");

                    b.Property<int?>("DiretorId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("IdadeMinima")
                        .HasColumnType("int");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaPrincipalId");

                    b.HasIndex("DiretorId");

                    b.HasIndex("GeneroId");

                    b.ToTable("DVD");
                });

            modelBuilder.Entity("EmprestimoDVD.Domain.Entidades.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmigoId")
                        .HasColumnType("int");

                    b.Property<int?>("DVDId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDevolver")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AmigoId");

                    b.HasIndex("DVDId");

                    b.ToTable("Emprestimo");
                });

            modelBuilder.Entity("EmprestimoDVD.Domain.Entidades.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("EmprestimoDVD.Domain.Entidades.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EmprestimoDVD.Domain.Entidades.Amigo", b =>
                {
                    b.HasBaseType("EmprestimoDVD.Domain.Entidades.Pessoa");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NumTelefone")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Amigo");
                });

            modelBuilder.Entity("EmprestimoDVD.Domain.Entidades.DVD", b =>
                {
                    b.HasOne("EmprestimoDVD.Domain.Entidades.Pessoa", "ArtistaPrincipal")
                        .WithMany()
                        .HasForeignKey("ArtistaPrincipalId");

                    b.HasOne("EmprestimoDVD.Domain.Entidades.Pessoa", "Diretor")
                        .WithMany()
                        .HasForeignKey("DiretorId");

                    b.HasOne("EmprestimoDVD.Domain.Entidades.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId");

                    b.Navigation("ArtistaPrincipal");

                    b.Navigation("Diretor");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("EmprestimoDVD.Domain.Entidades.Emprestimo", b =>
                {
                    b.HasOne("EmprestimoDVD.Domain.Entidades.Amigo", "Amigo")
                        .WithMany()
                        .HasForeignKey("AmigoId");

                    b.HasOne("EmprestimoDVD.Domain.Entidades.DVD", "DVD")
                        .WithMany()
                        .HasForeignKey("DVDId");

                    b.Navigation("Amigo");

                    b.Navigation("DVD");
                });
#pragma warning restore 612, 618
        }
    }
}
